### ISSUE TITLE
개발 도구 (라이브러리, 패키지) 설치

### ISSUE THREAD

**Issue by neptune588** [Gannies/Gannies_FrontEnd#1]
## ISSUE

라이브러리 밑 필요한 패키지들을 설치합니다.

## TODO

- [x] Vite 설치 
- [x] Styled-Components 설치
- [x] Axios 설치
- [x] React-Query 설치
- [x] Redux-Toolkit 설치
