### ISSUE TITLE
게시글 페이지 UI 제작 (기능 X)

### ISSUE THREAD

**Issue by neptune588** [Gannies/Gannies_FrontEnd#19]
## ISSUE

게시글 페이지에 필요한 UI 컴포넌트들을 제작합니다. (기능 X)

## TODO

- [x] 게시글 컴포넌트 제작
- [x] 페이지네이션을 위한 페이지 컴포넌트 제작
- [x] 정렬 컴포넌트 제작
