### ISSUE TITLE
props eslint오류 수정과 폰트 미적용 문제 밑 확장자 수정

### ISSUE THREAD

**Issue by neptune588** [Gannies/Gannies_FrontEnd#25]
## ISSUE

props eslint오류 수정과 폰트 미적용 문제를 해결합니다.

## TODO

- [ ] props eslint 표기 오류
- [ ] 폰트 미적용 문제 
- [ ] 스타일드 컴포넌트 정의부분 확장자 수정 jsx -> js
