### ISSUE TITLE
게시글 작성 페이지 UI 제작 (기능X)

### ISSUE THREAD

**Issue by neptune588** [Gannies/Gannies_FrontEnd#32]
## ISSUE

게시글 작성 페이지에 들어가는 컴포넌트, UI를 제작합니다(기능X, 레이아웃 O)

## TODO

- [x] UI 컴포넌트 제작
- [x] timyMce 라이브러리 설치 밑 해당 라이브러리 이용해 게시판 제작
- [x] 페이지 전체 레이아웃 완성
- [x] 병원찾기 모달 UI 제작
