### ISSUE TITLE
마이페이지 레이아웃 제작 + Post 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by neptune588** [Gannies/Gannies_FrontEnd#42]
## ISSUE
마이페이지 레이아웃을 만듭니다.
더불어 마이페이지에서 post컴포넌트가 쓰이기 때문에
post컴포넌트의 구조를 개편합니다. 
postList의 디자인도 개편합니다.

## TODO
- [x] 탭메뉴 박스 UI 제작
- [x] 회원정보 수정 레이아웃 제작
- [x] 비밀번호 변경 레이아웃 제작
- [x] 내가 쓴 게시글 레이아웃 제작
- [x] 내가 쓴 댓글 레이아웃 제작
- [x] post 컴포넌트 리팩토링 + postList디자인 변경 
- [x] scrap 컴포넌트 추가
