### ISSUE TITLE
관리자 페이지 레이아웃 제작 

### ISSUE THREAD

**Issue by neptune588** [Gannies/Gannies_FrontEnd#46]
## ISSUE

1. 관리자 페이지에 필요한 UI 컴포넌트 제작 
2. 관리자 페이지 레이아웃 제작

## TODO

- [x] 신고내역(게시글/댓글) 컴포넌트 제작
- [x] 신고내역(게시글/댓글) 모달 제작
- [x] 회원관리 컴포넌트 제작
- [x] 회원관리(정지사유입력) 모달 제작
- [x] 회원가입 승인 컴포넌트 제작
- [x] 게시물관리 컴포넌트 제작
