### ISSUE TITLE
게시글 상세 페이지 레이아웃 제작

### ISSUE THREAD

**Issue by neptune588** [Gannies/Gannies_FrontEnd#55]
## ISSUE

게시글 상세 페이지를 레이아웃을 제작합니다.

## TODO

- [x] 게시글 상단부 UI제작
- [x] 댓글 창 제작
- [x] 댓글 목록 제작
- [x] 수정/삭제 모달 제작
