### ISSUE TITLE
마이페이지 기능 추가

### ISSUE THREAD

**Issue by VaIice** [Gannies/Gannies_FrontEnd#62]
## ISSUE

마이페이지 각종 기능을 추가합니다.

## TODO

- [x] Input value 삽입
- [x] Icon 핸들링 함수 추가
- [x] 드롭다운 추가
- [x] Input focus 추가
- [x] Modal 추가
