### ISSUE TITLE
로그인, 로그아웃 API 연동

### ISSUE THREAD

**Issue by VaIice** [Gannies/Gannies_FrontEnd#66]
## ISSUE

이슈 개요를 입력 해주세요.

## TODO

- [x] 로그인 API 연동
- [ ] 이메일 찾기 -> 일치하는 정보가 없을 시 화면 수정
- [x] 휴대폰 번호 드롭다운 디자인 변경
- [x] 드롭다운 시 화살표 방향 변경
