### ISSUE TITLE
회원가입, 마이페이지 기능 구현

### ISSUE THREAD

**Issue by VaIice** [Gannies/Gannies_FrontEnd#69]
## ISSUE

회원가입, 마이페이지 기능 구현합니다.

## TODO

- [ ] api 파라미터 변경
- [ ] 회원가입 api 확인 (휴대폰 인증, 인증서 제외)
- [ ] 마이페이지 기능 구현
