### ISSUE TITLE
메인 홈페이지 디자인 변경 및 회원가입 구현

### ISSUE THREAD

**Issue by VaIice** [Gannies/Gannies_FrontEnd#79]
## ISSUE

메인 페이지 디자인 변경 및 회원 상태를 추가합니다.

## TODO

- [x] 메인 페이지 디자인 변경
- [x] 더보기 버튼 클릭 시 카테고리 변경 구현
- [x] 회원가입 인증서 업로드 구현
- [x] 회원가입 로직 구현
- [x] 인증서 미리보기 구현
