### ISSUE TITLE
최신 디자인 구현

### ISSUE THREAD

**Issue by VaIice** [Gannies/Gannies_FrontEnd#87]
## ISSUE

최신 디자인을 구현합니다.
## TODO

- [x] 내가 쓴 댓글 디자인 수정
- [x] 메인 페이지 디자인 구현
- [x] 마이페이지 회원 정보 알림 구현
- [x] 이메일 인증 모달창 디자인 구현
- [x] 인증서류 업로드 미리보기 구현
