### ISSUE TITLE
page, utill, api 등 부족한 기능 밑 디자인 보완 밑 추가

### ISSUE THREAD

**Issue by neptune588** [Gannies/Gannies_FrontEnd#91]
## ISSUE

1. 게시글 작성 부분 보완
2. 댓글 작성 시 작성된 댓글의 위치로 스크롤 이동 시키는 기능 + 페이지 이동 시 댓글 box 가장 상단부로 스크롤 이동 시키는 기능 추가
3. 회원관리에서 리스트를 클릭 시 해당 회원에 관한 detail한 정보를 띄우는 모달 제작 (디자인이 미완성이라 후순위)
4. 부족하거나 잘못된 디자인 수정, 보완

## TODO

- [x] 게시글 작성 부분 보완
- [x] 댓글 스크롤 MOVE기능 보완
- [x] 회원관리 detail info modal 제작 
- [x] 부족하거나 잘못된 디자인 보완
