### ISSUE TITLE
redux-persist 암호화 및 기타 에러 수정

### ISSUE THREAD

**Issue by VaIice** [Gannies/Gannies_FrontEnd#93]
## ISSUE

배포 후 남은 에러를 수정합니다.
## TODO

- [x] community 페이지 화면 흔들림 수정
- [x] 로그아웃 상태에서 상세 게시글 클릭 시 나오는 에러 수정
- [x] 404 페이지에서 URL에 따라 searchBar가 나오는 문제 수정
- [x] 메인 페이지 및 마이 페이지 리스트 hover시 색상 변경
- [x] 검색어가 없을 시 navigate -> alert로 변경
- [x] redux-persist 암호화
