### ISSUE TITLE
배포 후 프론트엔드 수정사항

### ISSUE THREAD

**Issue by VaIice** [Gannies/Gannies_FrontEnd#97]
## ISSUE

배포 후 프론트엔드 수정사항을 구현합니다.
## TODO

- [x] 메인페이지 - 바로가기 아이콘 '널디' -> '널리' 수정
- [x] 조회 수, 좋아요 수, 최신순, 작성순 띄어쓰기 통일
- [x] cryptoJS 반복 횟수 변경
