### ISSUE TITLE
노션 수정사항

### ISSUE THREAD

**Issue by VaIice** [Gannies/Gannies_FrontEnd#99]
## ISSUE

노션 수정사항을 구현합니다.

## TODO

- [x] 게시글이 존재하지 않을 시 404 페이지로 이동
- [x] 마이 페이지 - 게시글이 삭제된 경우 '삭제된 게시글입니다.' 표기
- [x] 마이 페이지 - 유효성 검사 추가
- [x] 마이 페이지 - 카테고리 색 변경 추가
